### ISSUE TITLE
Replacement for PVG612S

### ISSUE THREAD

**Issue by PicoElements** [jbilander/sdbox#16]
Hi,
i'm playing with rev1 of the board. Can you suggest me a replacement part for PVG612S ?
Thanks a lot,
PE

**Comment by jbilander** [comment]
Hi,
PVG612S is optional and only used if you are going to power via the barrel-jack (9V). You can find them on AliExpress, just search on PVG612S and you will find many stores that have them. Another way is to make a cable to power the unit from the external floppy port using a cable with a usb connector (Mini-USB for SDBox-v1)
https://github.com/jbilander/SDBox-v2#howto-get-5v-from-the-amigas-external-floppy-port-250-ma-max-lets-make-a-cable
Regards, J

**Comment by PicoElements** [comment]
Thank you! I will order some on Ali then. Not the best place but it's not a CPLD.. Great project by the way. :)

**Comment by salocinx** [comment]
Never had problems with CPLDs from aliexpress, but the CPLDs from utsource were mostly crap.

**Comment by PicoElements** [comment]
You're lucky mate, or i'm unlucky . Good to know better to avoid Utsource then, thanks! :)

**Comment by salocinx** [comment]
You are right, it's probably just gambling by ordering these second hand CPLDs from these stores ☺️
