### ISSUE TITLE
Could you provide a pre-compiled spisd.device ?

### ISSUE THREAD

**Issue by salocinx** [jbilander/sdbox#3]
Hi.
Thanks for sharing this great project!
I am not able to compile `spisd.device`, would it be possible to upload a pre-compiled file?

**Comment by jbilander** [comment]
Hi,
It is available in the zip-file under "Releases"
https://github.com/jbilander/sdbox/releases

**Comment by salocinx** [comment]
Great! Thanks a lot! Closed.
