### ISSUE TITLE
Amiga hangs while booting when SD0 is placed in DH0:Devs/DOSDrivers and sdbox not connected

### ISSUE THREAD

**Issue by salocinx** [jbilander/sdbox#4]
Hi

I meanwhile managed to run the `sdbox` on my Amiga 1200 with Blizzard IV 030 and 64MB Fast-RAM. Very cool !!

However, if I place the `SD0` mount list in `DH0:Devs/DOSDrivers` and the `sdbox` is **not** connected to the Amiga, the machine somewhen hangs during the boot sequence (black screen, no additional information).

Any idea why this happens and a possible work-around?

**Comment by jbilander** [comment]
Hi, nice you got it working. Yes this is a known TODO. Check comment in code here:

https://github.com/jbilander/sdbox/blob/master/common/spi-par.c#L48

**Comment by salocinx** [comment]
Great, thanks for the hint! I am currently setting up an Ubuntu 16.04 i386 machine. Maybe I can support you. Let's see.

**Comment by salocinx** [comment]
Uhm... getting error while trying to build the m68k toolchain. The following are not available anymore:
```

http://server.owl.de/~frank/tags/vasm1_8d.tar.gz
http://server.owl.de/~frank/tags/vlink0_16a.tar.gz
http://server.owl.de/~frank/tags/vbcc0_9fP1.tar.gz
```

Some idea?

**Comment by salocinx** [comment]
[Here's the solution for the missing files](https://github.com/adtools/amigaos-cross-toolchain/issues/102).

**Comment by salocinx** [comment]
I made a crude test and it works. Booting without device attached. Will think about a more elegant way.
```
        uint16_t timeout = 65535;
        uint8_t ctrl = *cia_b_pra;
	while (ctrl & IDLE_MASK) {
		ctrl ^= CLOCK_MASK;
		*cia_b_pra = ctrl;
		ctrl = *cia_b_pra;
                timeout--;
                if(timeout==0) break;
	}
```

**Comment by jbilander** [comment]
Hi, nice work. Please make a pull-request with your fix added when you are happy with your solution and I will merge it after having verified it works for me too.

**Comment by salocinx** [comment]
I handed in a new pull-request with a more elegant way using the timer sources.

**Comment by jbilander** [comment]
Thank you, I will take a look and see if it works for me too, and then merge and make a new 0.4 build. That is the plan.

**Comment by salocinx** [comment]
Thanks!
